//GOOGLE_CLIENT_ID=Google web client id, for login with google on Android
//BASE_URL=Application base URL
//SERVER_URL=Application base URL
//CLIENT_ID=Client id for juspay
//MERCHANT_ID=Merchant id for juspay
//MERCHANT_KEY_ID=Merchant key id for juspay
//ENV=Current application env, ['dev', 'prod']
// ASSISTANT_ID=Slang labs assistance id for voice search
// API_KEY=Slang labs assistance id for voice search
