export const CATEGORIES: any = [
  {
    id: '1',
    name: 'Fashion',
    shortName: 'Fashion',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png',
    routeName: 'Fashion',
    domain: 'ONDC:RET12',
  },
  {
    id: '2',
    name: 'Grocery',
    shortName: 'Grocery',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/grocery.png',
    routeName: 'Grocery',
    domain: 'ONDC:RET10',
  },
  {
    id: '3',
    name: 'Electronics',
    shortName: 'Electronics',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/electronis.png',
    routeName: 'Electronics',
    domain: 'ONDC:RET14',
  },
  {
    id: '4',
    name: 'Food & Beverage',
    shortName: 'F&B',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/food_beverage.png',
    routeName: 'F&B',
    domain: 'ONDC:RET11',
  },
  {
    id: '5',
    name: 'Home & Decor',
    shortName: 'Home & Decor',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png',
    routeName: 'Home & Decor',
    domain: 'ONDC:RET16',
  },
  {
    id: '6',
    name: 'Health & Wellness',
    shortName: 'Health & Wellness',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/health_wellness.png',
    routeName: 'Health & Wellness',
    domain: 'ONDC:RET18',
  },
  {
    id: '7',
    name: 'Beauty & Personal Care',
    shortName: 'BPC',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/beauty_personal_care.png',
    routeName: 'BPC',
    domain: 'ONDC:RET13',
  },
  {
    id: '9',
    name: 'Appliances',
    shortName: 'Appliances',
    Icon: 'https://d2v00mt5yqy11h.cloudfront.net/categories/appliances.png',
    routeName: 'Appliances',
    domain: 'ONDC:RET15',
  },
];
